### PR TITLE
Remove note about slack

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
It did not catch on and I was confused by it.

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
On a related note, how active is the newsletter? Maybe relying on meetup is easier because it does not require being active on so many channels.

**Comment by mads-hartmann** [comment]
@Leonidas-from-XIV We used it back in the day to catch the people who weren't happy signing up for meetup.com but I'd be totally happy killing the newsletter. I think keeping the overhead low for the organisers is the top priority

**Comment by Leonidas-from-XIV** [comment]
> I think keeping the overhead low for the organisers is the top priority

Yes, that's exactly why I am asking 😄 I'd like to keep the number of channels minimal, so ideally Meetup.com, the website (would be amazing if it could generate RSS so people can subscribe) and maybe the Twitter account.

**Comment by mads-hartmann** [comment]
@Leonidas-from-XIV Right now it's a static HTML file so you can easily generate a static XML file for the RSS feed ;) Alternatively maybe we should switch to jekyll on simply use a Github page with a custom domain (that's a slightly bigger task though)

**Pull request merged**
